// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs4GjTeDUB3h5a6n_XjTuzPfHDWsYgW6c',
    appId: '1:162180021634:web:81e7c145da3819efe9239b',
    messagingSenderId: '162180021634',
    projectId: 'fblab-8408f',
    authDomain: 'fblab-8408f.firebaseapp.com',
    storageBucket: 'fblab-8408f.firebasestorage.app',
    measurementId: 'G-6X2KME0078',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLD7yMHbsutjtanTUSfGNzBslZGvQMYxg',
    appId: '1:162180021634:android:e050679a6413d0b7e9239b',
    messagingSenderId: '162180021634',
    projectId: 'fblab-8408f',
    storageBucket: 'fblab-8408f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGH1uPPI9ignooyJLxt9GDbGuGQjeb5RQ',
    appId: '1:162180021634:ios:2cb94b0ffd9c92dae9239b',
    messagingSenderId: '162180021634',
    projectId: 'fblab-8408f',
    storageBucket: 'fblab-8408f.firebasestorage.app',
    iosBundleId: 'com.example.facebookUi',
  );
}
